/**
 * Flowchart node IDs used throughout the application
 */
export const NODE_IDS = {
  START: 'START',
  SUCCESS: 'SUCCESS',
  SURGERY: 'SURGERY',
  STACK_INSERT: 'STACK_INSERT',
  STACK_REMOVE: 'STACK_REMOVE',
  IVUS_WIRE_FLEX_YES: 'IVUS_WIRE_FLEX_YES',
  IVUS_WIRE_FLEX_NO: 'IVUS_WIRE_FLEX_NO',
  IVUS_CATHETER_ADVANCE_PROMPT: 'IVUS_CATHETER_ADVANCE_PROMPT',
  IVUS_CATHETER_NO_ADVANCE: 'IVUS_CATHETER_NO_ADVANCE',
  IVUS_CATHETER_ADVANCE: 'IVUS_CATHETER_ADVANCE',
  CATHETER_BLOCK: 'CATHETER_BLOCK',
  CATHETER_BLOCK_FAILURE: 'CATHETER_BLOCK_FAILURE',
  LOW_RISK_DEFORMATION: 'LOW_RISK_DEFORMATION',
} as const;

export type NodeId = typeof NODE_IDS[keyof typeof NODE_IDS];
